#!/bin/bash

hero="rancho"
villan="virus"

echo " 3 idiots ka hero hai $hero"

echo "3idiots ka villian hai $viilian"

#shell / enviorment variable 

echo "current logged in user $USER"

read -p "rancho ch purn nav kay hot?" fullname

echo "Racho ch purn nav $fullname hot"
